### ISSUE TITLE
Getting angularjs errors after running it

### ISSUE THREAD

**Issue by ambujpunn** [netanelgilad/meteor-ionic-example#10]
I cloned the repo and ran a "meteor update". after updating, I ran the app, but then I was given an errors in my console log:

![screen shot 2015-03-31 at 11 14 59 pm](https://cloud.githubusercontent.com/assets/704434/6935555/1d91d93a-d7fc-11e4-89cf-d1b08edd9657.png)

Is there a reason why this is happening?

**Comment by ambujpunn** [comment]
@netanelgilad do you know why this is happening?

**Comment by netanelgilad** [comment]
I'll be checking that later today.. Probably issues with the newer version
of angular-meteor.

**Comment by elmor34** [comment]
I 've solved the problem. Now it works with the latesr version 1.1.
Only urigo:ionic and urigo:angular need to be added.
Changed :

Packages to :
```
meteor-platform
urigo:ionic
urigo:angular
```

and app bootstrap to :
```
    Meteor.startup(function ()
    {
      angular.bootstrap(document, ['starter']);
    });

angular.module('starter', ['angular-meteor','ionic'] )

.run(['$ionicPlatform',function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if(window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
  });
}])
```

**Comment by netanelgilad** [comment]
Hey guys,
sorry it took me so long but I updated the example to the latest versions in meteor and angular-meteor.
Check it out! should work with no errors at all now.

**Comment by ambujpunn** [comment]
Thanks @netanelgilad! It's working now :) Btw I've also created a simple git repo that integrates Ionic&Angular with Meteor: https://github.com/ambujpunn/meteorionic

It also does the trick in using @Urigo's ```urigo:angular``` and ```urigo:ionic``` packages. If anyone has such problems again, please feel free to look at both of these repos :)
:beers:

**Comment by netanelgilad** [comment]
Awesome @ambujpunn! Try PRing the readme of urigo:ionic to reference your example.

**Comment by ambujpunn** [comment]
Thanks @netanelgilad! I've created a PR including links to both our repos: https://github.com/ambujpunn/meteor-ionic/pull/1

I think they can both be very useful to many folks out there!

**Comment by ambujpunn** [comment]
Thanks @netanelgilad! I've sent a PR including both our repo's as reference:
