### ISSUE TITLE
How do I deploy on android?

### ISSUE THREAD

**Issue by jdmswong** [netanelgilad/meteor-ionic-example#12]
```meteor run android``` throws the following error:
```Can't run on the following platforms on Windows: android```

```ionic run android``` works on other ionic projects, how do I fix this?

For background I'm using windows 7 SP1

Thanks!

**Comment by Urigo** [comment]
The problem is that Meteor Cordova doesn't support windows yet.
The good news is that Meteor 1.2 that comes out very soon solves this!

**Comment by netanelgilad** [comment]
@jdmswong Meteor 1.2 is now finally out! check out if your problems were fixed in the new version.

**Comment by jdmswong** [comment]
I no longer use windows, issue closed :)

**Comment by netanelgilad** [comment]
@jdmswong nice one ;)
