### ISSUE TITLE
navigation view

### ISSUE THREAD

**Issue by franckbirba** [netanelgilad/meteor-ionic-example#4]
Hi Urigo, thank you for this port, i am starting using it, but i can't find how to change the main view, as the exemple doesn't show it. I tried to use urlrouter and stateprovider but can't make it work...
any idea?

**Comment by phaggood** [comment]
I created a sample using ui-router and the layout urigo gives in the tutorial for angular apps; it builds and runs with no error but it doesn't appear to use any of the routing; I've used ionic and angular for a while but I'm new to meteor so the way it loads javascript is still opaque to me.  
https://github.com/phaggood/ionmeteorsample

**Comment by phaggood** [comment]
Okay, I got ionic + meteor + angular working together all the way thru  http://angularjs.meteor.com/tutorial-02/step_11; the ionic-nav-view will page thru using ui-router's states.  The current problem I have is I can't figure out how to get 'meteor run android' to download the correct version of org.apache.cordova.console, I found a temp file /.meteor/local/build-cordova-temp/star.json which has:

 "cordovaDependencies": {
        "org.apache.cordova.console": "0.2.10",
 which I changed to 2.13 but I still get:

Error: version not found: 0.2.10 : org.apache.cordova.console/0.2.10

I even tried 

meteor add cordova:com.phonegap.plugins.console@0.2.13

which appeared to run correctly but didn't change the config which is still looking for the old version.

**Comment by Urigo** [comment]
@phaggood looks like it's a Meteor error.
Please open an issue there and reference it here

**Comment by Urigo** [comment]
I've updated to example to include also ui-router and it works.

It is a very simple example so if you want to add more stuff to it I would be very happy.

Closing for now as it all seem to work and @phaggood 's problem is Meteor related

**Comment by phaggood** [comment]
https://github.com/meteor/meteor/issues/3755
