### ISSUE TITLE
iOS issue

### ISSUE THREAD

**Issue by hadarADP** [netanelgilad/meteor-ionic-example#5]
Hi Netanel,
This works perfect on Android and in the browser but failing on ios emulator and iPhone device. I am getting the following error:

[Error] SyntaxError: Unexpected token '<' (ng-cordova_plugins.js, line 1)
When I look at ng-cordova_plugins.js it looks like an HTML file rather than a js file:

<!DOCTYPE html>

....

Any idea?

Thank you!

**Comment by Urigo** [comment]
@hadarADP  Just updated the example, can you check again please?

**Comment by netanelgilad** [comment]
@hadarADP Hope you get to check this again as I don't have a mac or an iphone :(.
It seems like meteor couldn't find ng-corodva_plugins and served the index.html file instead and that's why you get that HTML file (it's only a guess...).
waiting for your answer..

**Comment by Urigo** [comment]
closing, @hadarADP please re-open if still persists
