### ISSUE TITLE
Problem Replicating Example With Newest Releases

### ISSUE THREAD

**Issue by nspangler** [netanelgilad/meteor-ionic-example#6]
Great example! However I am trying to replicate the example using the newest meteor and packages.
![screen shot 2015-01-14 at 5 35 30 pm](https://cloud.githubusercontent.com/assets/5549886/5760999/930c7b68-9c95-11e4-833a-52f6c51f7022.png)

I am trying to build just a simple side-menu basing my code off of this repo:

index.html:

    <body>
        <div>

        <ion-side-menus>
            
            <ion-side-menu-content>
                <ion-header-bar class="bar-dark">
                    <h1 class="title">Todo</h1>
                </ion-header-bar>
                <ion-content>
                </ion-content>
            </ion-side-menu-content>

            
            <ion-side-menu side="left">
                <ion-header-bar class="bar-dark">
                    <h1 class="title">Projects</h1>
                </ion-header-bar>
            </ion-side-menu>

        </ion-side-menus>

       </div>
     </body>

app.js

      if (Meteor.isClient) {

        var app = angular.module('todo', ['angular-meteor', 'ionic'], function($interpolateProvider) {
           $interpolateProvider.startSymbol('[[');
           $interpolateProvider.endSymbol(']]');
       });

        app.controller("TodoCtrl", ['$scope', '$collection', '$ionicSideMenuDelegate', function ($scope, $collection, $ionicSideMenuDelegate) {

        $scope.toggleProjects = function () {
              $ionicSideMenuDelegate.toggleLeft();
         };
       }]);

}

The result is this:

![screen shot 2015-01-14 at 5 32 59 pm](https://cloud.githubusercontent.com/assets/5549886/5761167/c960ffa8-9c96-11e4-88a0-5d107c31f8da.png)

**Comment by netanelgilad** [comment]
@nspangler I'm planning to update the repository hopefully this weekend.
Any way look at the answer here: https://github.com/Urigo/meteor-ionic/issues/34

**Comment by Urigo** [comment]
The example is updated now, should be fixed.
Please re-open is case of a problem
