### ISSUE TITLE
Uncaught ReferenceError: angularMeteor is not defined

### ISSUE THREAD

**Issue by brugnara** [netanelgilad/meteor-ionic-example#7]
I'm getting this issue.

```js
var app = angular.module('tt.app', ['ngCordova.plugins.datePicker']);
angularMeteor.requires.push('tt.app'); // this fails!
```

Thanks.

**Comment by linhkurt** [comment]
I got the same issue, searching around but haven't found solution yet! :(

**Comment by linhkurt** [comment]
@netanelgilad could you please help me out?

**Comment by netanelgilad** [comment]
Ill check it out later today and ill update the example to the new angular
package version

**Comment by Urigo** [comment]
Just updated the example to fix this issue.
@brugnara @linhkurt Please re-open in case of a problem.

**Comment by brugnara** [comment]
@Urigo many thanks. I'll check asap.
Have a nice day.
